config/routes.rb
Mongoapp::Application.routes.draw do  
  
  resources :mongotests

  resources :forecasts do
    collection do
      get 'summary'
      get 'search'
      get 'aggregate'
    end
  end
  
  get "home/index"

  root :to => 'home#index'

    

end

app/models/mongotest.rb
class Mongotest
  include MongoMapper::Document

  key :key, String
  key :value, Integer

end

app/controllers/mongotests_controller.rb
class MongotestsController < ApplicationController
  # GET /mongotests
  # GET /mongotests.json
  def index
    @mongotests = Mongotest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mongotests }
    end
  end

  # GET /mongotests/1
  # GET /mongotests/1.json
  def show
    @mongotest = Mongotest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mongotest }
    end
  end

  # GET /mongotests/new
  # GET /mongotests/new.json
  def new
    @mongotest = Mongotest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mongotest }
    end
  end

  # GET /mongotests/1/edit
  def edit
    @mongotest = Mongotest.find(params[:id])
  end

  # POST /mongotests
  # POST /mongotests.json
  def create
    @mongotest = Mongotest.new(params[:mongotest])

    respond_to do |format|
      if @mongotest.save
        format.html { redirect_to @mongotest, notice: 'Mongotest was successfully created.' }
        format.json { render json: @mongotest, status: :created, location: @mongotest }
      else
        format.html { render action: "new" }
        format.json { render json: @mongotest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mongotests/1
  # PUT /mongotests/1.json
  def update
    @mongotest = Mongotest.find(params[:id])

    respond_to do |format|
      if @mongotest.update_attributes(params[:mongotest])
        format.html { redirect_to @mongotest, notice: 'Mongotest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mongotest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mongotests/1
  # DELETE /mongotests/1.json
  def destroy
    @mongotest = Mongotest.find(params[:id])
    @mongotest.destroy

    respond_to do |format|
      format.html { redirect_to mongotests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mongotests_helper.rb
module MongotestsHelper
end

app/views/mongotests/_form.html.erb
<%= form_for(@mongotest) do |f| %>
  <% if @mongotest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mongotest.errors.count, "error") %> prohibited this mongotest from being saved:</h2>

      <ul>
      <% @mongotest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mongotests/edit.html.erb
<h1>Editing mongotest</h1>

<%= render 'form' %>

<%= link_to 'Show', @mongotest %> |
<%= link_to 'Back', mongotests_path %>

app/views/mongotests/index.html.erb
<h1>Listing mongotests</h1>

<table>
  <tr>
    <th>Key</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mongotests.each do |mongotest| %>
  <tr>
    <td><%= mongotest.key %></td>
    <td><%= mongotest.value %></td>
    <td><%= link_to 'Show', mongotest %></td>
    <td><%= link_to 'Edit', edit_mongotest_path(mongotest) %></td>
    <td><%= link_to 'Destroy', mongotest, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mongotest', new_mongotest_path %>

app/views/mongotests/new.html.erb
<h1>New mongotest</h1>

<%= render 'form' %>

<%= link_to 'Back', mongotests_path %>

app/views/mongotests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Key:</b>
  <%= @mongotest.key %>
</p>

<p>
  <b>Value:</b>
  <%= @mongotest.value %>
</p>


<%= link_to 'Edit', edit_mongotest_path(@mongotest) %> |
<%= link_to 'Back', mongotests_path %>