config/routes.rb
Mongoapp::Application.routes.draw do  
  
  resources :mongotests

  resources :forecasts do
    collection do
      get 'summary'
      get 'search'
      get 'aggregate'
    end
  end
  
  get "home/index"

  root :to => 'home#index'

    

end

app/models/forecast.rb
class Forecast
  include MongoMapper::Document

  key :productid, Integer
  key :locationid, Integer
  key :divisionid, Integer
  key :calendarid, Integer
  key :productcategoryid, Integer
  key :startdate, Date
  key :enddate, Date
  key :optunitvol, Integer
  key :optrev, Float
  key :optgrossmargin, Float

end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController

  # GET /forecasts
  # GET /forecasts.json
  def index
  @forecasts = Forecast.where(:productid => 1).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @forecasts }
    end
  end
    
  # GET /forecasts/summary
  def summary
    @totalcount = Forecast.count
    @productcount = Forecast.sort(:productid.desc).first.productid
    #@divisioncount = MongoMapper.database.collection("forecasts").distinct("divisionid").count
    @divisioncount = Forecast.sort(:divisionid.desc).first.divisionid
    @calendarcount = Forecast.sort(:calendarid.desc).first.calendarid
    
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /forecasts/search
  # GET /forecasts/search.json
  def search
    
    @querystring = ""
    if params[:productid] && params[:productid] != ""
      @productid = params[:productid].to_i
      @querystring += ":productid => " + @productid.to_s
    end
    
    if params[:locationid] && params[:locationid] != ""
      @locationid = params[:locationid].to_i
      if @querystring != ""
        @querystring += ", "
      end
      @querystring += ":locationid => " + @locationid.to_s
    end
    
    if params[:divisionid] && params[:divisionid] != ""
      @divisionid = params[:divisionid].to_i
      if @querystring != ""
        @querystring += ", "
      end
      @querystring += ":divisionid => " + @divisionid.to_s
    end
    
    if params[:calendarid] && params[:calendarid] != ""
      @calendarid = params[:calendarid].to_i
      if @querystring != ""
        @querystring += ", "
      end
      @querystring += ":calendarid => " + @calendarid.to_s
    end
    
    if params[:beginstartdate] && params[:beginstartdate] != ""
      @beginstartdate = params[:beginstartdate]
      if @querystring != ""
        @querystring += ", "
      end
      @querystring += ":startdate.gt => \"" + @beginstartdate.to_s + "\""
    end
    if params[:endstartdate] && params[:endstartdate] != ""
      @endstartdate = params[:endstartdate]
      if @querystring != ""
        @querystring += ", "
      end
      @querystring += ":startdate.lt => \"" + @endstartdate.to_s + "\""
    end
    
    if params[:beginenddate] && params[:beginenddate] != ""
      @beginenddate = params[:beginenddate]
      if @querystring != ""
        @querystring += ", "
      end
      @querystring += ":enddate.gt => \"" + @beginenddate.to_s + "\""
    end
    if params[:endenddate] && params[:endenddate] != ""
      @endenddate = params[:endenddate]
      if @querystring != ""
        @querystring += ", "
      end
      @querystring += ":enddate.lt => \"" + @endenddate.to_s + "\""
    end
    
    if @productid || @locationid || @divisionid || @calendarid || @beginstartdate || @endstartdate || 
      @beginenddate || @endenddate
      @forecasts = eval ("Forecast.where(" + @querystring + ").limit(1000)")

      respond_to do |format|
        format.html # search.html.erb
        format.json { render json: @forecasts }
      end
    else
      @forecasts = ()
    end
    
  end
  
  # GET /forecasts/aggregate
  # GET /forecasts/aggregate.json
  def aggregate

    # intitialize aggregation types and releted reporting paramters
    @aggtype = ""
    if params[:aggtype] && params[:aggtype] == "pdwtodw"
      @aggtype = params[:aggtype]
      @headers = ["Division Id", "Calendar Id", "Volume", "Revenue", "Margin"]
    elsif params[:aggtype] && params[:aggtype] == "pdwtopd"
      @aggtype = params[:aggtype]
      @headers = ["ProductId", "DivisionId", "Volume", "Revenue", "Margin"]
    end
    
    # deal with aggregation request
    # based on the type, a aggregation collection is created - this will be used for future searches
    # NOTE: actual aggregations are kicked off by map-reduce here
    if params[:requesttype] && params[:requesttype] == "aggregation"

      if @aggtype == "pdwtodw"
        
        Aggregate.group_by_2keys(:divisionid, :calendarid,
          :optunitvol, :optrev, :optgrossmargin, 
          :out => @aggtype)

      elsif @aggtype == "pdwtopd"

        Aggregate.group_by_2keys(:productid, :divisionid, 
          :optunitvol, :optrev, :optgrossmargin, 
          :out => @aggtype)

      end
    
    
    # deal with search requests
    # based on the query filters, and aggregation to use, provide the result set
    elsif params[:requesttype] && params[:requesttype] == "search"
      @querystring = ""

      if params[:productid] && params[:productid] != ""
        @productid = params[:productid].to_i
        @querystring += "\"_id.productid\" => " + @productid.to_s
      end

      if params[:locationid] && params[:locationid] != ""
        @locationid = params[:locationid].to_i
        if @querystring != ""
          @querystring += ", "
        end
        @querystring += "\"_id.locationid\" => " + @locationid.to_s
      end

      if params[:divisionid] && params[:divisionid] != ""
        @divisionid = params[:divisionid].to_i
        if @querystring != ""
          @querystring += ", "
        end
        @querystring += "\"_id.divisionid\" => " + @divisionid.to_s
      end

      if params[:calendarid] && params[:calendarid] != ""
        @calendarid = params[:calendarid].to_i
        if @querystring != ""
          @querystring += ", "
        end
        @querystring += "\"_id.calendarid\" => " + @calendarid.to_s
      end

      #@aggtype = "plwtopdw"
      #@headers = ["Product Id", "Division Id", "Calendar Id", "Opt Revenue", "Opt Unit Volume", "Total Cost"]
      #@agg = eval ("MongoMapper.database.collection(\"" + @aggtype + "\").find(\"_id.productid\" => 1, \"_id.divisionid\" => 1)")
      @agg = eval ("MongoMapper.database.collection(\"" + @aggtype + "\").find(" + @querystring + ").limit(1000)")

      respond_to do |format|
        format.html # agregate.html.erb
        format.json { render json: @agg }
      end

    end

  end

  # GET /forecasts/1
  # GET /forecasts/1.json
  def show
    @forecast = Forecast.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @forecast }
    end
  end

  # GET /forecasts/new
  # GET /forecasts/new.json
  def new
    @forecast = Forecast.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @forecast }
    end
  end

  # GET /forecasts/1/edit
  def edit
    @forecast = Forecast.find(params[:id])
  end

  # POST /forecasts
  # POST /forecasts.json
  def create
    @forecast = Forecast.new(params[:forecast])

    respond_to do |format|
      if @forecast.save
        format.html { redirect_to @forecast, notice: 'Forecast was successfully created.' }
        format.json { render json: @forecast, status: :created, location: @forecast }
      else
        format.html { render action: "new" }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /forecasts/1
  # PUT /forecasts/1.json
  def update
    @forecast = Forecast.find(params[:id])

    respond_to do |format|
      if @forecast.update_attributes(params[:forecast])
        format.html { redirect_to @forecast, notice: 'Forecast was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forecasts/1
  # DELETE /forecasts/1.json
  def destroy
    @forecast = Forecast.find(params[:id])
    @forecast.destroy

    respond_to do |format|
      format.html { redirect_to forecasts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/views/forecasts/_form.html.erb
<%= form_for(@forecast) do |f| %>
  <% if @forecast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forecast.errors.count, "error") %> prohibited this forecast from being saved:</h2>

      <ul>
      <% @forecast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :productid %><br />
    <%= f.number_field :productid %>
  </div>
  <div class="field">
    <%= f.label :locationid %><br />
    <%= f.number_field :locationid %>
  </div>
  <div class="field">
    <%= f.label :calendarid %><br />
    <%= f.number_field :calendarid %>
  </div>
  <div class="field">
    <%= f.label :productcategoryid %><br />
    <%= f.number_field :productcategoryid %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br />
    <%= f.date_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br />
    <%= f.date_select :enddate %>
  </div>
  <div class="field">
    <%= f.label :divisionid %><br />
    <%= f.number_field :divisionid %>
  </div>
  <div class="field">
    <%= f.label :optrev %><br />
    <%= f.text_field :optrev %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forecasts/aggregate.html.erb
<h1>Mongo Aggregation</h1>

<br/>

<div class="field">
  <%= form_tag("aggregate", :method => "get") do %>
  	<%= hidden_field_tag 'requesttype', 'aggregation' %> 
  	<%= hidden_field_tag 'aggtype', 'pdwtodw' %> 
  	<%= submit_tag("Aggregate Product-Division-Week to Division-Week") %>	
  <% end %>
</div>
<div class="field">
  <%= form_tag("aggregate", :method => "get") do %>	
    <%= hidden_field_tag 'requesttype', 'aggregation' %> 
    <%= hidden_field_tag 'aggtype', 'pdwtopd' %> 
    <%= submit_tag("Aggregate Product-Division-Week to Product-Division") %>	
  <% end %>
</div>

<hr>

<%= form_tag("aggregate", :method => "get") do %>
  <%= hidden_field_tag 'requesttype', 'search' %> 
  <div class="field">
	<select name="aggtype">
	  <option value="">Please select Aggregation to use for searching:</option>
	  <option value="pdwtodw"
		<% if @aggtype == "pdwtodw" %> selected="selected"<% end %>
	  >Division Week</option>
	  <option value="pdwtopd"
		<% if @aggtype == "pdwtopd" %> selected="selected"<% end %>
	  >Product Division</option>
	</select>
  </div>

  <div class="field">
    <%= label_tag(:productid, "Product Id:") %><br />
  	<%= text_field_tag(:productid, params[:productid]) %>
  </div>
  <div class="field">
    <%= label_tag(:locationid, "Location Id:") %><br />
  	<%= text_field_tag(:locationid, params[:locationid]) %>
  </div>
  <div class="field">
    <%= label_tag(:divisionid, "Division Id:") %><br />
  	<%= text_field_tag(:divisionid, params[:divisionid]) %>
  </div>
  <div class="field">
    <%= label_tag(:calendarid, "Week Id:") %><br />
  	<%= text_field_tag(:calendarid, params[:calendarid]) %>
  </div>
  <div class="field">
	<%= submit_tag("Search") %>
  </div>
<% end %>

<br/>

<table>
	<% if @agg %>

		<!-- display header -->
		<tr>
			<% @headers.each do |header| %>
		  		<th><%= header %></th>
			<% end %>
		</tr>

		<!-- display rows -->
		<% @agg.each do |agg| %>
		  <tr>
		    <% agg['_id'].each do |aggkeys| %>
    	  	  <td><%= "#{aggkeys[1]}" %></td>	 	
 			<% end %>
		    <% agg['value'].each do |aggvalues| %>
    	  	  <td><%= "#{aggvalues[1]}" %></td>	 	
 			<% end %>
		  </tr>
		<% end %>
		
		
	<% end %>
</table>

<br><br>

<%= link_to 'Back', forecasts_path %>

app/views/forecasts/edit.html.erb
<h1>Editing forecast</h1>

<%= render 'form' %>

<%= link_to 'Show', @forecast %> |
<%= link_to 'Back', forecasts_path %>

app/views/forecasts/index.html.erb
<h1>Welcome to MongoDB performance evaluation page</h1>

<br/>
<br/>

<%= link_to 'Get data summary', summary_forecasts_path %>
<br/>
<br/>

<%= link_to 'Search (Lookups and Scans)', search_forecasts_path %>
<br/>
<br/>

<%= link_to 'Aggregation', aggregate_forecasts_path %>
<br/>
<br/>

app/views/forecasts/new.html.erb
<h1>New forecast</h1>

<%= render 'form' %>

<%= link_to 'Back', forecasts_path %>

app/views/forecasts/search.html.erb
<h1>Mongo Search</h1>


<%= form_tag("search", :method => "get") do %>
  <div class="field">
    <%= label_tag(:productid, "Product Id:") %><br />
  	<%= text_field_tag(:productid, params[:productid]) %>
  </div>
  <div class="field">
    <%= label_tag(:locationid, "Location Id:") %><br />
  	<%= text_field_tag(:locationid, params[:locationid]) %>
  </div>
  <div class="field">
    <%= label_tag(:divisionid, "Division Id:") %><br />
  	<%= text_field_tag(:divisionid, params[:divisionid]) %>
  </div>
  <div class="field">
    <%= label_tag(:calendarid, "Week Id:") %><br />
  	<%= text_field_tag(:calendarid, params[:calendarid]) %>
  </div>
  <div class="field">
    <%= label_tag("Start Date:") %><br />
  	After  <%= text_field_tag(:beginstartdate, params[:beginstartdate]) %>, 
  	Before <%= text_field_tag(:endstartdate, params[:endstartdate]) %>
  </div>
  <div class="field">
    <%= label_tag("End Date:") %><br />
  	After  <%= text_field_tag(:beginenddate, params[:beginenddate]) %>, 
  	Before <%= text_field_tag(:endenddate, params[:endenddate]) %>
  </div>
  <div class="field">
	<%= submit_tag("Search") %>
  </div>
<% end %>

<br/>

<table>
<% if @forecasts %>

<tr>
  <th>Productid</th>
  <th>Locationid</th>
  <th>Divisionid</th>
  <th>Calendarid</th>
  <th>Productcategoryid</th>
  <th>Startdate</th>
  <th>Enddate</th>
  <th>Volume</th>
  <th>Revenue</th>
  <th>GrossMargin</th>
  <th></th>
  <th></th>
  <th></th>
</tr>

<% @forecasts.each do |forecast| %>

  <tr>
    <td><%= forecast.productid %></td>
    <td><%= forecast.locationid %></td>
    <td><%= forecast.divisionid %></td>
    <td><%= forecast.calendarid %></td>
    <td><%= forecast.productcategoryid %></td>
    <td><%= forecast.startdate %></td>
    <td><%= forecast.enddate %></td>
    <td><%= forecast.optunitvol %></td>
    <td><%= forecast.optrev %></td>
    <td><%= forecast.optgrossmargin %></td>
    <td><%= link_to 'Show', forecast %></td>
    <td><%= link_to 'Edit', edit_forecast_path(forecast) %></td>
    <td><%= link_to 'Delete', forecast, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
<% end %>
</table>

<br><br>

<%= link_to 'Back', forecasts_path %>

app/views/forecasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Productid:</b>
  <%= @forecast.productid %>
</p>

<p>
  <b>Locationid:</b>
  <%= @forecast.locationid %>
</p>

<p>
  <b>Divisionid:</b>
  <%= @forecast.divisionid %>
</p>

<p>
  <b>Calendarid:</b>
  <%= @forecast.calendarid %>
</p>

<p>
  <b>Productcategoryid:</b>
  <%= @forecast.productcategoryid %>
</p>

<p>
  <b>Startdate:</b>
  <%= @forecast.startdate %>
</p>

<p>
  <b>Enddate:</b>
  <%= @forecast.enddate %>
</p>

<p>
  <b>Volume:</b>
  <%= @forecast.optunitvol %>
</p>

<p>
  <b>Revenue:</b>
  <%= @forecast.optrev %>
</p>

<p>
  <b>GrossMargin:</b>
  <%= @forecast.optgrossmargin %>
</p>

<%= link_to 'Edit', edit_forecast_path(@forecast) %> |
<%= link_to 'Back', forecasts_path %>

app/views/forecasts/summary.html.erb
<h1>Data Summary</h1>

<br><br>

<table>
  <tr>
    <th align='left'>Total Records</th>
    <th align='right'><%= @totalcount %></th>
  </tr>
  <tr><th colspan=2><br></th></tr>
  <tr>
    <th align='left'>Total Distinct Products</th>
    <th align='right'><%= @productcount %></th>
  </tr>
  <tr>
    <th align='left'>Total Distinct Divisions</th>
    <th align='right'><%= @divisioncount %></th>
  </tr>
  <tr>
    <th align='left'>Total Distinct Weeks</th>
    <th align='right'><%= @calendarcount %></th>
  </tr>
</table>

<br><br>

<%= link_to 'Back', forecasts_path %>